var baseUrl = "http://39.107.100.204:8888/"

var cityApi = {
    "市GDP增长率": "getCityGDPGrowthRate",
    "市GDP平均": "getCityGDPAverage",
    "市购房压力": "getHousePressure",
    "市GDP占省比例": "getCityGDPRatioOfProv",
    "市医疗覆盖率": "getCityMedicalCoverage",
    "国内生产总值": "getCityGDP",
    "在岗职工平均工资": "getCityAverageSalary",
    "商品房平均销售价格": "getCityAverageHousePrice",
    "第一产业增加值": "getCityPrimaryIndustryIncr",
    "第二产业增加值": "getCitySecondaryIndustryIncr",
    "第三产业增加值": "getCityThirdIndustryIncr",
    "总人口": "getCityPopulation",
    "医院、卫生院数": "getCityNumOfHospital",
    "社会商品零售总额": "getCityRetailTotalSale"
};

var provinceApi = {
    '地区生产总值': 'getRegionGDP',
    '第一产业增加值': 'getPrimaryIndustryIncr',
    '第二产业增加值': 'getSecondaryIndustryIncr',
    '第三产业增加值': 'getThirdIndustryIncr',
    '在岗职工平均工资':'getProvAverageSalary',
    '商品房平均销售价格':'getProvAverageHousePrice',
    '城市绿地面积':'getProvGreenArea',
    '平均寿命':'getAverageExpectedLifetime',
    '年末常住人口':'getPermResident',
    '城镇人口':'getTownPopulation',
    '乡村人口':'getCountryPopulation',
    '医院数量': 'getNumOfHospital',
    '零售业销售总额':'getRetailTotalSale',
    '居民人均可支配收入':'getDisposableIncome',
    '社会福利企业机构数':'getNumOfWelfareFirm',
    '居民消费水平':'getConsumptionLevel',
    '省GDP增长率': 'getProvGDPGrowthRate'
};

var regionMap = {
    "北京市": "北京",
    "天津市": "天津",
    "河北省": "河北",
    "山西省": "山西",
    "内蒙古自治区": "内蒙古",
    "辽宁省": "辽宁",
    "吉林省": "吉林",
    "黑龙江省": "黑龙江",
    "上海市": "上海",
    "江苏省": "江苏",
    "浙江省": "浙江",
    "安徽省": "安徽",
    "福建省": "福建",
    "江西省": "江西",
    "山东省": "山东",
    "河南省": "河南",
    "湖北省": "湖北",
    "湖南省": "湖南",
    "广东省": "广东",
    "广西壮族自治区": "广西",
    "海南省": "海南",
    "重庆市": "重庆",
    "四川省": "四川",
    "贵州省": "贵州",
    "云南省": "云南",
    "西藏自治区": "西藏",
    "陕西省": "陕西",
    "甘肃省": "甘肃",
    "青海省": "青海",
    "宁夏回族自治区": "宁夏",
    "新疆维吾尔自治区": "新疆"
}

var regionReverseMap = {
    "北京": "北京市",
    "天津": "天津市",
    "河北": "河北省",
    "山西": "山西省",
    "内蒙古": "内蒙古自治区",
    "辽宁": "辽宁省",
    "吉林": "吉林省",
    "黑龙江": "黑龙江省",
    "上海": "上海市",
    "江苏": "江苏省",
    "浙江": "浙江省",
    "安徽": "安徽省",
    "福建": "福建省",
    "江西": "江西省",
    "山东": "山东省",
    "河南": "河南省",
    "湖北": "湖北省",
    "湖南": "湖南省",
    "广东": "广东省",
    "广西": "广西壮族自治区",
    "海南": "海南省",
    "重庆": "重庆市",
    "四川": "四川省",
    "贵州": "贵州省",
    "云南": "云南省",
    "西藏": "西藏自治区",
    "陕西": "陕西省",
    "甘肃": "甘肃省",
    "青海": "青海省",
    "宁夏": "宁夏回族自治区",
    "新疆": "新疆维吾尔自治区"
}